# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{  name: 'Chicago' }, {  name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
password = BCrypt::Password.create("123456")

users = User.create([
  { username: 'Chad', email: 'chad@nyu.edu', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Tyler', email: 'tyler@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Trish', email: 'trish@nyu.edu', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Adam', email: 'adam@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Lexi', email: 'lexi@gmail.com', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Hannah', email: 'hannah@gmail.com', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Liz', email: 'liz@gmail.com', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Austin', email: 'austin@embryriddle.edu', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Logan', email: 'logan@whoknows.com', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Carl', email: 'carl@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Conz', email: 'conz@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Jonathan', email: 'jonathan@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Tommy', email: 'tommy@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Ariel', email: 'ariel@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Chris', email: 'chris@aa.io', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' },
  { username: 'Erika', email: 'erika@fsu.edu', password_digest: BCrypt::Password.create('123456'), month: '03', day: '23', year: '1989', sex_orientation: 'Gay', gender: 'Female', country: 'United States', zip_code: '32303' }
  ])

profiles = Profile.create([
  { user_id: User.all[0].id },
  { user_id: User.all[1].id },
  { user_id: User.all[2].id },
  { user_id: User.all[3].id },
  { user_id: User.all[4].id },
  { user_id: User.all[5].id },
  { user_id: User.all[6].id },
  { user_id: User.all[7].id },
  { user_id: User.all[8].id },
  { user_id: User.all[9].id },
  { user_id: User.all[10].id },
  { user_id: User.all[11].id },
  { user_id: User.all[12].id },
  { user_id: User.all[13].id },
  { user_id: User.all[14].id },
  { user_id: User.all[15].id }
  ])

likes = Like.create([
  { profile_id: 2, liker_id: 1},
  { profile_id: 3, liker_id: 1},
  { profile_id: 4, liker_id: 1},
  { profile_id: 5, liker_id: 1},
  { profile_id: 6, liker_id: 1},
  { profile_id: 7, liker_id: 1},
  { profile_id: 8, liker_id: 1},
  { profile_id: 9, liker_id: 1},
  { profile_id: 10, liker_id: 1},
  { profile_id: 11, liker_id: 1},
  { profile_id: 12, liker_id: 1},
  { profile_id: 13, liker_id: 1},
  { profile_id: 14, liker_id: 1},
  { profile_id: 15, liker_id: 1},
  { profile_id: 16, liker_id: 1},

  { profile_id: 1, liker_id: 2},
  { profile_id: 3, liker_id: 2},
  { profile_id: 4, liker_id: 2},
  { profile_id: 5, liker_id: 2},
  { profile_id: 6, liker_id: 2},
  { profile_id: 7, liker_id: 2},
  { profile_id: 8, liker_id: 2},
  { profile_id: 9, liker_id: 2},
  { profile_id: 10, liker_id: 2},
  { profile_id: 11, liker_id: 2},
  { profile_id: 12, liker_id: 2},
  { profile_id: 13, liker_id: 2},
  { profile_id: 14, liker_id: 2},
  { profile_id: 15, liker_id: 2},
  { profile_id: 16, liker_id: 2},

  { profile_id: 1, liker_id: 3},
  { profile_id: 2, liker_id: 3},
  { profile_id: 4, liker_id: 3},
  { profile_id: 5, liker_id: 3},
  { profile_id: 6, liker_id: 3},
  { profile_id: 7, liker_id: 3},
  { profile_id: 8, liker_id: 3},
  { profile_id: 9, liker_id: 3},
  { profile_id: 10, liker_id: 3},
  { profile_id: 11, liker_id: 3},
  { profile_id: 12, liker_id: 3},
  { profile_id: 13, liker_id: 3},
  { profile_id: 14, liker_id: 3},
  { profile_id: 15, liker_id: 3},
  { profile_id: 16, liker_id: 3},

  { profile_id: 1, liker_id: 4},
  { profile_id: 2, liker_id: 4},
  { profile_id: 3, liker_id: 4},
  { profile_id: 5, liker_id: 4},
  { profile_id: 6, liker_id: 4},
  { profile_id: 7, liker_id: 4},
  { profile_id: 8, liker_id: 4},
  { profile_id: 9, liker_id: 4},
  { profile_id: 10, liker_id: 4},
  { profile_id: 11, liker_id: 4},
  { profile_id: 12, liker_id: 4},
  { profile_id: 13, liker_id: 4},
  { profile_id: 14, liker_id: 4},
  { profile_id: 15, liker_id: 4},
  { profile_id: 16, liker_id: 4},

  { profile_id: 1, liker_id: 5},
  { profile_id: 2, liker_id: 5},
  { profile_id: 3, liker_id: 5},
  { profile_id: 4, liker_id: 5},
  { profile_id: 6, liker_id: 5},
  { profile_id: 7, liker_id: 5},
  { profile_id: 8, liker_id: 5},
  { profile_id: 9, liker_id: 5},
  { profile_id: 10, liker_id: 5},
  { profile_id: 11, liker_id: 5},
  { profile_id: 12, liker_id: 5},
  { profile_id: 13, liker_id: 5},
  { profile_id: 14, liker_id: 5},
  { profile_id: 15, liker_id: 5},
  { profile_id: 16, liker_id: 5},

  { profile_id: 1, liker_id: 6},
  { profile_id: 2, liker_id: 6},
  { profile_id: 3, liker_id: 6},
  { profile_id: 4, liker_id: 6},
  { profile_id: 5, liker_id: 6},
  { profile_id: 7, liker_id: 6},
  { profile_id: 8, liker_id: 6},
  { profile_id: 9, liker_id: 6},
  { profile_id: 10, liker_id: 6},
  { profile_id: 11, liker_id: 6},
  { profile_id: 12, liker_id: 6},
  { profile_id: 13, liker_id: 6},
  { profile_id: 14, liker_id: 6},
  { profile_id: 15, liker_id: 6},
  { profile_id: 16, liker_id: 6},

  { profile_id: 1, liker_id: 7},
  { profile_id: 2, liker_id: 7},
  { profile_id: 3, liker_id: 7},
  { profile_id: 4, liker_id: 7},
  { profile_id: 5, liker_id: 7},
  { profile_id: 7, liker_id: 7},
  { profile_id: 8, liker_id: 7},
  { profile_id: 9, liker_id: 7},
  { profile_id: 10, liker_id: 7},
  { profile_id: 11, liker_id: 7},
  { profile_id: 12, liker_id: 7},
  { profile_id: 13, liker_id: 7},
  { profile_id: 14, liker_id: 7},
  { profile_id: 15, liker_id: 7},
  { profile_id: 16, liker_id: 7},

  { profile_id: 1, liker_id: 8},
  { profile_id: 2, liker_id: 8},
  { profile_id: 3, liker_id: 8},
  { profile_id: 4, liker_id: 8},
  { profile_id: 5, liker_id: 8},
  { profile_id: 6, liker_id: 8},
  { profile_id: 7, liker_id: 8},
  { profile_id: 9, liker_id: 8},
  { profile_id: 10, liker_id: 8},
  { profile_id: 11, liker_id: 8},
  { profile_id: 12, liker_id: 8},
  { profile_id: 13, liker_id: 8},
  { profile_id: 14, liker_id: 8},
  { profile_id: 15, liker_id: 8},
  { profile_id: 16, liker_id: 8},

  { profile_id: 1, liker_id: 9},
  { profile_id: 2, liker_id: 9},
  { profile_id: 3, liker_id: 9},
  { profile_id: 4, liker_id: 9},
  { profile_id: 5, liker_id: 9},
  { profile_id: 6, liker_id: 9},
  { profile_id: 7, liker_id: 9},
  { profile_id: 8, liker_id: 9},
  { profile_id: 10, liker_id: 9},
  { profile_id: 11, liker_id: 9},
  { profile_id: 12, liker_id: 9},
  { profile_id: 13, liker_id: 9},
  { profile_id: 14, liker_id: 9},
  { profile_id: 15, liker_id: 9},
  { profile_id: 16, liker_id: 9},

  { profile_id: 1, liker_id: 10},
  { profile_id: 2, liker_id: 10},
  { profile_id: 3, liker_id: 10},
  { profile_id: 4, liker_id: 10},
  { profile_id: 5, liker_id: 10},
  { profile_id: 6, liker_id: 10},
  { profile_id: 7, liker_id: 10},
  { profile_id: 8, liker_id: 10},
  { profile_id: 9, liker_id: 10},
  { profile_id: 11, liker_id: 10},
  { profile_id: 12, liker_id: 10},
  { profile_id: 13, liker_id: 10},
  { profile_id: 14, liker_id: 10},
  { profile_id: 15, liker_id: 10},
  { profile_id: 16, liker_id: 10},

  { profile_id: 1, liker_id: 11},
  { profile_id: 2, liker_id: 11},
  { profile_id: 3, liker_id: 11},
  { profile_id: 4, liker_id: 11},
  { profile_id: 5, liker_id: 11},
  { profile_id: 6, liker_id: 11},
  { profile_id: 7, liker_id: 11},
  { profile_id: 8, liker_id: 11},
  { profile_id: 9, liker_id: 11},
  { profile_id: 10, liker_id: 11},
  { profile_id: 12, liker_id: 11},
  { profile_id: 13, liker_id: 11},
  { profile_id: 14, liker_id: 11},
  { profile_id: 15, liker_id: 11},
  { profile_id: 16, liker_id: 11},

  { profile_id: 1, liker_id: 12},
  { profile_id: 2, liker_id: 12},
  { profile_id: 3, liker_id: 12},
  { profile_id: 4, liker_id: 12},
  { profile_id: 5, liker_id: 12},
  { profile_id: 6, liker_id: 12},
  { profile_id: 7, liker_id: 12},
  { profile_id: 8, liker_id: 12},
  { profile_id: 9, liker_id: 12},
  { profile_id: 10, liker_id: 12},
  { profile_id: 11, liker_id: 12},
  { profile_id: 13, liker_id: 12},
  { profile_id: 14, liker_id: 12},
  { profile_id: 15, liker_id: 12},
  { profile_id: 16, liker_id: 12},

  { profile_id: 1, liker_id: 13},
  { profile_id: 2, liker_id: 13},
  { profile_id: 3, liker_id: 13},
  { profile_id: 4, liker_id: 13},
  { profile_id: 5, liker_id: 13},
  { profile_id: 6, liker_id: 13},
  { profile_id: 7, liker_id: 13},
  { profile_id: 8, liker_id: 13},
  { profile_id: 9, liker_id: 13},
  { profile_id: 10, liker_id: 13},
  { profile_id: 11, liker_id: 13},
  { profile_id: 12, liker_id: 13},
  { profile_id: 14, liker_id: 13},
  { profile_id: 15, liker_id: 13},
  { profile_id: 16, liker_id: 13},

  { profile_id: 1, liker_id: 14},
  { profile_id: 2, liker_id: 14},
  { profile_id: 3, liker_id: 14},
  { profile_id: 4, liker_id: 14},
  { profile_id: 5, liker_id: 14},
  { profile_id: 6, liker_id: 14},
  { profile_id: 7, liker_id: 14},
  { profile_id: 8, liker_id: 14},
  { profile_id: 9, liker_id: 14},
  { profile_id: 10, liker_id: 14},
  { profile_id: 11, liker_id: 14},
  { profile_id: 12, liker_id: 14},
  { profile_id: 13, liker_id: 14},
  { profile_id: 15, liker_id: 14},
  { profile_id: 16, liker_id: 14},

  { profile_id: 1, liker_id: 15},
  { profile_id: 2, liker_id: 15},
  { profile_id: 3, liker_id: 15},
  { profile_id: 4, liker_id: 15},
  { profile_id: 5, liker_id: 15},
  { profile_id: 6, liker_id: 15},
  { profile_id: 7, liker_id: 15},
  { profile_id: 8, liker_id: 15},
  { profile_id: 9, liker_id: 15},
  { profile_id: 10, liker_id: 15},
  { profile_id: 11, liker_id: 15},
  { profile_id: 12, liker_id: 15},
  { profile_id: 13, liker_id: 15},
  { profile_id: 14, liker_id: 15},
  { profile_id: 16, liker_id: 15},

  { profile_id: 1, liker_id: 16},
  { profile_id: 2, liker_id: 16},
  { profile_id: 3, liker_id: 16},
  { profile_id: 4, liker_id: 16},
  { profile_id: 5, liker_id: 16},
  { profile_id: 6, liker_id: 16},
  { profile_id: 7, liker_id: 16},
  { profile_id: 8, liker_id: 16},
  { profile_id: 9, liker_id: 16},
  { profile_id: 10, liker_id: 16},
  { profile_id: 11, liker_id: 16},
  { profile_id: 12, liker_id: 16},
  { profile_id: 13, liker_id: 16},
  { profile_id: 14, liker_id: 16},
  { profile_id: 15, liker_id: 16},
  ])

messages = Message.create([
  { sender_id: 1, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 1, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 2, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 2, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 3, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 3, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 4, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 4, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 5, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 5, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 6, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 6, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 7, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 7, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 8, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 8, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 9, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 9, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 10, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 10, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 11, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 11, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 12, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 12, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 13, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 13, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 14, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 15, title: "Test", body: "Test" },
  { sender_id: 14, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 15, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 15, recipient_id: 16, title: "Test", body: "Test" },

  { sender_id: 16, recipient_id: 1, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 2, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 3, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 4, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 5, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 6, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 7, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 8, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 9, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 10, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 11, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 12, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 13, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 14, title: "Test", body: "Test" },
  { sender_id: 16, recipient_id: 15, title: "Test", body: "Test" }
  ])

questions = Question.create([
  ## 1-10
  { title: "If you somehow were able to get paid enough money for perpetually being a college student, would you spend a lifetime taking classes and learning?" },
  { title: "Regardless of future plans, what's more interesting to you right now?" },
  { title: "Is astrological sign at all important in a match?" },
  { title: "How willing are you to meet someone from OkCupid in person?" },
  { title: "Have you smoked a cigarette in the last 6 months?" },
  { title: "Which would you rather be?" },
  { title: "Could you date someone who was really messy?" },
  { title: "Could you date someone who does drugs?" },
  { title: "Would you strongly prefer to go out with someone of your own skin color / racial background?" },
  { title: "Do you believe your country would be more or less safe if every adult owned a gun?" },
  ## 11-20
  { title: "About how long do you want your next relationship to last?" },
  { title: "Would you consider sleeping with someone on the first date?" },
  { title: "Would you consider having an open relationship (i.e., one where you can see other people)?" },
  { title: "Are you happy with your life?" },
  { title: "Say you've started seeing someone you really like. As far as you're concerned, how long will it take before you have sex?" },
  { title: "Rate your self-confidence:" },
  { title: "What is the most exciting thing about getting to know someone new?" },
  { title: "How important is religion/God in your life?" },
  { title: "Which makes for a better relationship?" },
  { title: "Do you enjoy intense intellectual conversations?" },
  ## 21-30
  { title: "Do you enjoy discussing politics?" },
  { title: "Is jealousy healthy in a relationship?" },
  { title: "Would you prefer good things happened, or interesting things?" },
  { title: "In a certain light, wouldn't nuclear war be exciting?" },
  { title: "Do you like scary movies?" },
  { title: "Are you a cat person or a dog person?" },
  { title: "Which word describes you better?" },
  { title: "Do spelling mistakes annoy you?" },
  { title: "If you turn a left-handed glove inside out, it fits..." },
  { title: "In the line “Wherefore art thou Romeo?,” what does “wherefore” mean?" },
  ## 31-40
  { title: "STALE is to STEAL as 89475 is to..." },
  { title: "What's your relationship with marijuana?" },
  { title: "What's your deal with harder drugs (stuff beyond pot)?" },
  { title: "How frequently do you drink alcohol?" },
  { title: "Are you either vegetarian or vegan?" },
  { title: "Which best describes your political beliefs?" },
  { title: "Should burning your country's flag be illegal?" },
  { title: "Should evolution and creationism be taught side-by-side in school?" },
  { title: "Do you think homosexuality is a sin?" },
  { title: "For you personally, is abortion an option in case of an accidental pregnancy?" },
  ## 41-50
  { title: "Once you're intimate, how often would you and your significant other have sex?" },
  { title: "Would you need to sleep with someone before you considered marrying them?" },
  { title: "Do you want your partner to be kinkier than you?" },
  { title: "How often are you open with your feelings?" },
  { title: "Could you date someone who was really quiet?" },
  { title: "How often do you keep your promises?" },
  { title: "Is it a requirement that you communicate every day with your significant other (via phone, text, in person, whatever)?" },
  { title: "Which of these is likely to make you more nervous?" },
  { title: "Do you often make jokes that offend more uptight people?" },
  { title: "Could you date someone who already has children from a previous relationship?" },
  ## 51-60
  { title: "How do you feel about documentaries?" },
  { title: "If you had to name your greatest motivation in life thus far, what would it be?" },
  { title: "Do you believe morality is universal, or relative?" },
  { title: "Would you consider dating someone who has vocalized a strong negative bias toward a certain race of people?" },
  { title: "Do you believe contraception is morally wrong?" },
  { title: "How often do you brush your teeth?" },
  { title: "Do you space out or daydream a lot?" },
  { title: "Which of these options most closely describes what you're looking for in your next relationship?" },
  { title: "How important are your political beliefs to you?" },
  { title: "How much can intelligence turn you on?" },
  ## 61-70
  { title: "Have you ever had a sexual encounter with someone of the same sex?" },
  { title: "Are you looking for a partner to have children with?" },
  { title: "How often do you use Facebook?" },
  { title: "Are you an aspiring actor/artist/writer or other creative type?" },
  { title: "Which superpower would you rather have?" },
  { title: "How long do your romantic relationships usually last?" },
  { title: "Which is bigger?" },
  { title: "If you were to die, would whoever goes through your personal belongings be shocked by what they find?" },
  { title: "Do you keep a budget of your finances?" },
  { title: "How frequently do you bathe or shower?" },
  ## 71-80
  { title: "What is next in this series? 1, 4, 10, 19, 31, _" },
  { title: "Would the world be a better place if people with low IQs were not allowed to reproduce?" },
  { title: "How do you feel about falling in love?" },
  { title: "Do you like to cuddle?" },
  { title: "Is smoking disgusting?" },
  { title: "How open are you to trying new things in bed?" },
  { title: "If you don't do anything at all for an entire day, how does that make you feel?" },
  { title: "How much influence or control do your parents have over your life?" }
  ])

question_choices = QuestionChoice.create([
  { question_id: 1, body: "Yes" },
  { question_id: 1, body: "No" },
  { question_id: 2, body: "Sex" },
  { question_id: 2, body: "Love" },
  { question_id: 3, body: "Yes" },
  { question_id: 3, body: "No" },
  { question_id: 4, body: "Totally willing!" },
  { question_id: 4, body: "Hesitant, but I'd certainly consider it." },
  { question_id: 4, body: "I'm not interested in meeting in person." },
  { question_id: 5, body: "Yes" },
  { question_id: 5, body: "No" },
  { question_id: 6, body: "Normal" },
  { question_id: 6, body: "Weird" },
  { question_id: 7, body: "Yes" },
  { question_id: 7, body: "No" },
  { question_id: 8, body: "No" },
  { question_id: 8, body: "Yes, but only soft stuff like marijuana" },
  { question_id: 8, body: "Yes" },
  { question_id: 9, body: "Yes" },
  { question_id: 9, body: "No" },
  { question_id: 10, body: "More safe" },
  { question_id: 10, body: "Less safe" },
  { question_id: 10, body: "Neither / unsure" },
  { question_id: 11, body: "One night" },
  { question_id: 11, body: "A few months to a year" },
  { question_id: 11, body: "Several years" },
  { question_id: 11, body: "The rest of my life" },
  { question_id: 12, body: "Yes" },
  { question_id: 12, body: "No" },
  { question_id: 13, body: "Yes" },
  { question_id: 13, body: "No" },
  { question_id: 14, body: "Yes" },
  { question_id: 14, body: "No" },
  { question_id: 15, body: "1-2 dates" },
  { question_id: 15, body: "3-5 dates" },
  { question_id: 15, body: "6 or more dates" },
  { question_id: 15, body: "Only after the wedding" },
  { question_id: 16, body: "Very, very high" },
  { question_id: 16, body: "Higher than average" },
  { question_id: 16, body: "Average" },
  { question_id: 16, body: "Below average" },
  { question_id: 17, body: "Discovering your shared interests" },
  { question_id: 17, body: "Discovering their body" },
  { question_id: 18, body: "Extremely important" },
  { question_id: 18, body: "Somewhat important" },
  { question_id: 18, body: "Not very important" },
  { question_id: 18, body: "Not at all important" },
  { question_id: 19, body: "Passion" },
  { question_id: 19, body: "Dedication" },
  { question_id: 20, body: "Yes" },
  { question_id: 20, body: "No" },
  { question_id: 21, body: "Yes" },
  { question_id: 21, body: "No" },
  { question_id: 22, body: "Yes" },
  { question_id: 22, body: "No" },
  { question_id: 23, body: "Good" },
  { question_id: 23, body: "Interesting" },
  { question_id: 24, body: "Yes, it would." },
  { question_id: 24, body: "No, it wouldn't." },
  { question_id: 25, body: "Yes" },
  { question_id: 25, body: "No" },
  { question_id: 26, body: "Cats" },
  { question_id: 26, body: "Dogs" },
  { question_id: 26, body: "Both" },
  { question_id: 26, body: "Neither" },
  { question_id: 27, body: "Carefree" },
  { question_id: 27, body: "Intense" },
  { question_id: 28, body: "Yes" },
  { question_id: 28, body: "No" },
  { question_id: 29, body: "On my left hand" },
  { question_id: 29, body: "On my right hand" },
  { question_id: 30, body: "Why" },
  { question_id: 30, body: "Where" },
  { question_id: 30, body: "How" },
  { question_id: 30, body: "Who cares / wtf?" },
  { question_id: 31, body: "89457" },
  { question_id: 31, body: "98547" },
  { question_id: 31, body: "89754" },
  { question_id: 31, body: "89547" },
  { question_id: 32, body: "I smoke regularly." },
  { question_id: 32, body: "I smoke occasionally." },
  { question_id: 32, body: "I smoked in the past, but no longer." },
  { question_id: 32, body: "Never." },
  { question_id: 33, body: "I do drugs regularly." },
  { question_id: 33, body: "I do drugs occasionally." },
  { question_id: 33, body: "I've done drugs in the past, but no longer." },
  { question_id: 33, body: "I never do drugs." },
  { question_id: 34, body: "Very often" },
  { question_id: 34, body: "Sometimes" },
  { question_id: 34, body: "Rarely" },
  { question_id: 34, body: "Never" },
  { question_id: 35, body: "Yes" },
  { question_id: 35, body: "No" },
  { question_id: 36, body: "Liberal / Left-wing" },
  { question_id: 36, body: "Centrist" },
  { question_id: 36, body: "Conservative / Right-wing" },
  { question_id: 36, body: "Other" },
  { question_id: 37, body: "Yes" },
  { question_id: 37, body: "No" },
  { question_id: 38, body: "Yes, students should hear both sides" },
  { question_id: 38, body: "No, creationism has no place in schools" },
  { question_id: 38, body: "No, evolution has no place in schools" },
  { question_id: 39, body: "Yes" },
  { question_id: 39, body: "No" },
  { question_id: 40, body: "Yes" },
  { question_id: 40, body: "No" },
  { question_id: 41, body: "Every day" },
  { question_id: 41, body: "About every other day" },
  { question_id: 41, body: "Once or twice a week" },
  { question_id: 41, body: "A few times a month or less" },
  { question_id: 42, body: "Yes" },
  { question_id: 42, body: "No" },
  { question_id: 43, body: "Yes" },
  { question_id: 43, body: "No" },
  { question_id: 43, body: "Not possible" },
  { question_id: 44, body: "Always" },
  { question_id: 44, body: "Usually" },
  { question_id: 44, body: "Rarely" },
  { question_id: 44, body: "Never" },
  { question_id: 45, body: "Yes" },
  { question_id: 45, body: "No" },
  { question_id: 46, body: "Always" },
  { question_id: 46, body: "Whenever possible" },
  { question_id: 46, body: "Usually" },
  { question_id: 46, body: "When convenient" },
  { question_id: 47, body: "Yes, no matter what" },
  { question_id: 47, body: "Yes, unless otherwise specified" },
  { question_id: 47, body: "No, it's not necessary" },
  { question_id: 47, body: "No, I'd prefer not to communicate daily" },
  { question_id: 48, body: "A promising first date" },
  { question_id: 48, body: "An important interview" },
  { question_id: 49, body: "Yes" },
  { question_id: 49, body: "No" },
  { question_id: 50, body: "Yes" },
  { question_id: 50, body: "No" },
  { question_id: 51, body: "Yay!" },
  { question_id: 51, body: "Okay" },
  { question_id: 51, body: "NO." },
  { question_id: 52, body: "Love" },
  { question_id: 52, body: "Wealth" },
  { question_id: 52, body: "Expression" },
  { question_id: 52, body: "Knowledge" },
  { question_id: 53, body: "Universal" },
  { question_id: 53, body: "Relative" },
  { question_id: 54, body: "Yes" },
  { question_id: 54, body: "No" },
  { question_id: 54, body: "It depends on which race" },
  { question_id: 55, body: "Yes" },
  { question_id: 55, body: "No" },
  { question_id: 56, body: "Twice or more a day" },
  { question_id: 56, body: "Once a day" },
  { question_id: 56, body: "Only on days I feel like it" },
  { question_id: 56, body: "Rarely / never" },
  { question_id: 57, body: "All the time" },
  { question_id: 57, body: "Rarely / never" },
  { question_id: 57, body: "Sometimes" },
  { question_id: 58, body: "Someone to come home to" },
  { question_id: 58, body: "Someone to go out with" },
  { question_id: 58, body: "Someone for tonight" },
  { question_id: 59, body: "Very important" },
  { question_id: 59, body: "Somewhat important" },
  { question_id: 59, body: "A little important" },
  { question_id: 59, body: "Not at all important" },
  { question_id: 60, body: "A lot!" },
  { question_id: 60, body: "A bit." },
  { question_id: 60, body: "Intelligence does nothing for me either way." },
  { question_id: 60, body: "Intelligence turns me off." },
  { question_id: 61, body: "Yes, and I enjoyed myself." },
  { question_id: 61, body: "Yes, and I did not enjoy myself." },
  { question_id: 61, body: "No, and I would never." },
  { question_id: 61, body: "No, but I would like to." },
  { question_id: 62, body: "Yes" },
  { question_id: 62, body: "No" },
  { question_id: 63, body: "I'm a very active user." },
  { question_id: 63, body: "I'm a somewhat active user." },
  { question_id: 63, body: "I rarely use it." },
  { question_id: 63, body: "I never use it." },
  { question_id: 64, body: "Yes" },
  { question_id: 64, body: "No" },
  { question_id: 65, body: "Flight" },
  { question_id: 65, body: "Invisibility" },
  { question_id: 66, body: "0-6 months" },
  { question_id: 66, body: "6-12 months" },
  { question_id: 66, body: "12+ months" },
  { question_id: 66, body: "I've never been in a relationship" },
  { question_id: 67, body: "The Earth" },
  { question_id: 67, body: "The Sun" },
  { question_id: 68, body: "Yes." },
  { question_id: 68, body: "No." },
  { question_id: 68, body: "Maybe a little bit." },
  { question_id: 69, body: "Yes" },
  { question_id: 69, body: "No" },
  { question_id: 69, body: "Sometimes" },
  { question_id: 70, body: "At least once a day." },
  { question_id: 70, body: "Usually daily. I skip some." },
  { question_id: 70, body: "A couple times a week." },
  { question_id: 70, body: "Once a week or less." },
  { question_id: 71, body: "36" },
  { question_id: 71, body: "48" },
  { question_id: 71, body: "46" },
  { question_id: 71, body: "Don't know / don't care" },
  { question_id: 72, body: "Yes" },
  { question_id: 72, body: "No" },
  { question_id: 73, body: "I love it and want it very much" },
  { question_id: 73, body: "I try to avoid it" },
  { question_id: 73, body: "I like to just let it happen" },
  { question_id: 73, body: "I'm indifferent / not sure" },
  { question_id: 74, body: "Yes." },
  { question_id: 74, body: "No." },
  { question_id: 74, body: "Sometimes - it depends." },
  { question_id: 75, body: "Yes" },
  { question_id: 75, body: "No" },
  { question_id: 76, body: "Very open. I'll try anything once." },
  { question_id: 76, body: "I'm open, but I don't get too crazy." },
  { question_id: 76, body: "Hesitant, but it might happen." },
  { question_id: 76, body: "Not at all." },
  { question_id: 77, body: "Good" },
  { question_id: 77, body: "Bad" },
  { question_id: 78, body: "I am my own person." },
  { question_id: 78, body: "I consider their opinion but go my own way." },
  { question_id: 78, body: "I almost always do what my parents think is best." },
  { question_id: 78, body: "I always do what my parents say." }
  ])

question_answers = QuestionAnswer.create([
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },
  { question_id: Question.all.sample.id, question_choice_id: QuestionChoice.all.sample.id, user_id: User.all.sample.id, importance: 1 },

  ])
