# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
password = BCrypt::Password.create("123456")

users = User.create([
  { username: 'Chad', email: 'chad@nyu.edu', password_digest: BCrypt::Password.create('123456') },
  { username: 'Tyler', email: 'tyler@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Trish', email: 'trish@nyu.edu', password_digest: BCrypt::Password.create('123456') },
  { username: 'Adam', email: 'adam@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Lexi', email: 'lexi@gmail.com', password_digest: BCrypt::Password.create('123456') },
  { username: 'Hannah', email: 'hannah@gmail.com', password_digest: BCrypt::Password.create('123456') },
  { username: 'Liz', email: 'liz@gmail.com', password_digest: BCrypt::Password.create('123456') },
  { username: 'Austin', email: 'austin@embryriddle.edu', password_digest: BCrypt::Password.create('123456') },
  { username: 'Logan', email: 'logan@whoknows.com', password_digest: BCrypt::Password.create('123456') },
  { username: 'Carl', email: 'carl@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Conz', email: 'conz@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Jonathan', email: 'jonathan@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Tommy', email: 'tommy@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Ariel', email: 'ariel@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Chris', email: 'chris@aa.io', password_digest: BCrypt::Password.create('123456') },
  { username: 'Erika', email: 'erika@fsu.edu', password_digest: BCrypt::Password.create('123456') }
  ])

profiles = Profile.create([
  { user_id: 1 },
  { user_id: 2 },
  { user_id: 3 },
  { user_id: 4 },
  { user_id: 5 },
  { user_id: 6 },
  { user_id: 7 },
  { user_id: 8 },
  { user_id: 9 },
  { user_id: 10 },
  { user_id: 11 },
  { user_id: 12 },
  { user_id: 13 },
  { user_id: 14 },
  { user_id: 15 },
  { user_id: 16 }
  ])

likes = Like.create([
  { profile_id: 2, liker_id: 1},
  { profile_id: 3, liker_id: 1},
  { profile_id: 4, liker_id: 1},
  { profile_id: 5, liker_id: 1},
  { profile_id: 6, liker_id: 1},
  { profile_id: 7, liker_id: 1},
  { profile_id: 8, liker_id: 1},
  { profile_id: 9, liker_id: 1},
  { profile_id: 10, liker_id: 1},
  { profile_id: 11, liker_id: 1},
  { profile_id: 12, liker_id: 1},
  { profile_id: 13, liker_id: 1},
  { profile_id: 14, liker_id: 1},
  { profile_id: 15, liker_id: 1},
  { profile_id: 16, liker_id: 1},

  { profile_id: 1, liker_id: 2},
  { profile_id: 3, liker_id: 2},
  { profile_id: 4, liker_id: 2},
  { profile_id: 5, liker_id: 2},
  { profile_id: 6, liker_id: 2},
  { profile_id: 7, liker_id: 2},
  { profile_id: 8, liker_id: 2},
  { profile_id: 9, liker_id: 2},
  { profile_id: 10, liker_id: 2},
  { profile_id: 11, liker_id: 2},
  { profile_id: 12, liker_id: 2},
  { profile_id: 13, liker_id: 2},
  { profile_id: 14, liker_id: 2},
  { profile_id: 15, liker_id: 2},
  { profile_id: 16, liker_id: 2},

  { profile_id: 1, liker_id: 3},
  { profile_id: 2, liker_id: 3},
  { profile_id: 4, liker_id: 3},
  { profile_id: 5, liker_id: 3},
  { profile_id: 6, liker_id: 3},
  { profile_id: 7, liker_id: 3},
  { profile_id: 8, liker_id: 3},
  { profile_id: 9, liker_id: 3},
  { profile_id: 10, liker_id: 3},
  { profile_id: 11, liker_id: 3},
  { profile_id: 12, liker_id: 3},
  { profile_id: 13, liker_id: 3},
  { profile_id: 14, liker_id: 3},
  { profile_id: 15, liker_id: 3},
  { profile_id: 16, liker_id: 3},

  { profile_id: 1, liker_id: 4},
  { profile_id: 2, liker_id: 4},
  { profile_id: 3, liker_id: 4},
  { profile_id: 5, liker_id: 4},
  { profile_id: 6, liker_id: 4},
  { profile_id: 7, liker_id: 4},
  { profile_id: 8, liker_id: 4},
  { profile_id: 9, liker_id: 4},
  { profile_id: 10, liker_id: 4},
  { profile_id: 11, liker_id: 4},
  { profile_id: 12, liker_id: 4},
  { profile_id: 13, liker_id: 4},
  { profile_id: 14, liker_id: 4},
  { profile_id: 15, liker_id: 4},
  { profile_id: 16, liker_id: 4},

  { profile_id: 1, liker_id: 5},
  { profile_id: 2, liker_id: 5},
  { profile_id: 3, liker_id: 5},
  { profile_id: 4, liker_id: 5},
  { profile_id: 6, liker_id: 5},
  { profile_id: 7, liker_id: 5},
  { profile_id: 8, liker_id: 5},
  { profile_id: 9, liker_id: 5},
  { profile_id: 10, liker_id: 5},
  { profile_id: 11, liker_id: 5},
  { profile_id: 12, liker_id: 5},
  { profile_id: 13, liker_id: 5},
  { profile_id: 14, liker_id: 5},
  { profile_id: 15, liker_id: 5},
  { profile_id: 16, liker_id: 5},

  { profile_id: 1, liker_id: 6},
  { profile_id: 2, liker_id: 6},
  { profile_id: 3, liker_id: 6},
  { profile_id: 4, liker_id: 6},
  { profile_id: 5, liker_id: 6},
  { profile_id: 7, liker_id: 6},
  { profile_id: 8, liker_id: 6},
  { profile_id: 9, liker_id: 6},
  { profile_id: 10, liker_id: 6},
  { profile_id: 11, liker_id: 6},
  { profile_id: 12, liker_id: 6},
  { profile_id: 13, liker_id: 6},
  { profile_id: 14, liker_id: 6},
  { profile_id: 15, liker_id: 6},
  { profile_id: 16, liker_id: 6},

  { profile_id: 1, liker_id: 7},
  { profile_id: 2, liker_id: 7},
  { profile_id: 3, liker_id: 7},
  { profile_id: 4, liker_id: 7},
  { profile_id: 5, liker_id: 7},
  { profile_id: 7, liker_id: 7},
  { profile_id: 8, liker_id: 7},
  { profile_id: 9, liker_id: 7},
  { profile_id: 10, liker_id: 7},
  { profile_id: 11, liker_id: 7},
  { profile_id: 12, liker_id: 7},
  { profile_id: 13, liker_id: 7},
  { profile_id: 14, liker_id: 7},
  { profile_id: 15, liker_id: 7},
  { profile_id: 16, liker_id: 7},

  { profile_id: 1, liker_id: 8},
  { profile_id: 2, liker_id: 8},
  { profile_id: 3, liker_id: 8},
  { profile_id: 4, liker_id: 8},
  { profile_id: 5, liker_id: 8},
  { profile_id: 6, liker_id: 8},
  { profile_id: 7, liker_id: 8},
  { profile_id: 9, liker_id: 8},
  { profile_id: 10, liker_id: 8},
  { profile_id: 11, liker_id: 8},
  { profile_id: 12, liker_id: 8},
  { profile_id: 13, liker_id: 8},
  { profile_id: 14, liker_id: 8},
  { profile_id: 15, liker_id: 8},
  { profile_id: 16, liker_id: 8},

  { profile_id: 1, liker_id: 9},
  { profile_id: 2, liker_id: 9},
  { profile_id: 3, liker_id: 9},
  { profile_id: 4, liker_id: 9},
  { profile_id: 5, liker_id: 9},
  { profile_id: 6, liker_id: 9},
  { profile_id: 7, liker_id: 9},
  { profile_id: 8, liker_id: 9},
  { profile_id: 10, liker_id: 9},
  { profile_id: 11, liker_id: 9},
  { profile_id: 12, liker_id: 9},
  { profile_id: 13, liker_id: 9},
  { profile_id: 14, liker_id: 9},
  { profile_id: 15, liker_id: 9},
  { profile_id: 16, liker_id: 9},

  { profile_id: 1, liker_id: 10},
  { profile_id: 2, liker_id: 10},
  { profile_id: 3, liker_id: 10},
  { profile_id: 4, liker_id: 10},
  { profile_id: 5, liker_id: 10},
  { profile_id: 6, liker_id: 10},
  { profile_id: 7, liker_id: 10},
  { profile_id: 8, liker_id: 10},
  { profile_id: 9, liker_id: 10},
  { profile_id: 11, liker_id: 10},
  { profile_id: 12, liker_id: 10},
  { profile_id: 13, liker_id: 10},
  { profile_id: 14, liker_id: 10},
  { profile_id: 15, liker_id: 10},
  { profile_id: 16, liker_id: 10},

  { profile_id: 1, liker_id: 11},
  { profile_id: 2, liker_id: 11},
  { profile_id: 3, liker_id: 11},
  { profile_id: 4, liker_id: 11},
  { profile_id: 5, liker_id: 11},
  { profile_id: 6, liker_id: 11},
  { profile_id: 7, liker_id: 11},
  { profile_id: 8, liker_id: 11},
  { profile_id: 9, liker_id: 11},
  { profile_id: 10, liker_id: 11},
  { profile_id: 12, liker_id: 11},
  { profile_id: 13, liker_id: 11},
  { profile_id: 14, liker_id: 11},
  { profile_id: 15, liker_id: 11},
  { profile_id: 16, liker_id: 11},

  { profile_id: 1, liker_id: 12},
  { profile_id: 2, liker_id: 12},
  { profile_id: 3, liker_id: 12},
  { profile_id: 4, liker_id: 12},
  { profile_id: 5, liker_id: 12},
  { profile_id: 6, liker_id: 12},
  { profile_id: 7, liker_id: 12},
  { profile_id: 8, liker_id: 12},
  { profile_id: 9, liker_id: 12},
  { profile_id: 10, liker_id: 12},
  { profile_id: 11, liker_id: 12},
  { profile_id: 13, liker_id: 12},
  { profile_id: 14, liker_id: 12},
  { profile_id: 15, liker_id: 12},
  { profile_id: 16, liker_id: 12},

  { profile_id: 1, liker_id: 13},
  { profile_id: 2, liker_id: 13},
  { profile_id: 3, liker_id: 13},
  { profile_id: 4, liker_id: 13},
  { profile_id: 5, liker_id: 13},
  { profile_id: 6, liker_id: 13},
  { profile_id: 7, liker_id: 13},
  { profile_id: 8, liker_id: 13},
  { profile_id: 9, liker_id: 13},
  { profile_id: 10, liker_id: 13},
  { profile_id: 11, liker_id: 13},
  { profile_id: 12, liker_id: 13},
  { profile_id: 14, liker_id: 13},
  { profile_id: 15, liker_id: 13},
  { profile_id: 16, liker_id: 13},

  { profile_id: 1, liker_id: 14},
  { profile_id: 2, liker_id: 14},
  { profile_id: 3, liker_id: 14},
  { profile_id: 4, liker_id: 14},
  { profile_id: 5, liker_id: 14},
  { profile_id: 6, liker_id: 14},
  { profile_id: 7, liker_id: 14},
  { profile_id: 8, liker_id: 14},
  { profile_id: 9, liker_id: 14},
  { profile_id: 10, liker_id: 14},
  { profile_id: 11, liker_id: 14},
  { profile_id: 12, liker_id: 14},
  { profile_id: 13, liker_id: 14},
  { profile_id: 15, liker_id: 14},
  { profile_id: 16, liker_id: 14},

  { profile_id: 1, liker_id: 15},
  { profile_id: 2, liker_id: 15},
  { profile_id: 3, liker_id: 15},
  { profile_id: 4, liker_id: 15},
  { profile_id: 5, liker_id: 15},
  { profile_id: 6, liker_id: 15},
  { profile_id: 7, liker_id: 15},
  { profile_id: 8, liker_id: 15},
  { profile_id: 9, liker_id: 15},
  { profile_id: 10, liker_id: 15},
  { profile_id: 11, liker_id: 15},
  { profile_id: 12, liker_id: 15},
  { profile_id: 13, liker_id: 15},
  { profile_id: 14, liker_id: 15},
  { profile_id: 16, liker_id: 15},

  { profile_id: 1, liker_id: 16},
  { profile_id: 2, liker_id: 16},
  { profile_id: 3, liker_id: 16},
  { profile_id: 4, liker_id: 16},
  { profile_id: 5, liker_id: 16},
  { profile_id: 6, liker_id: 16},
  { profile_id: 7, liker_id: 16},
  { profile_id: 8, liker_id: 16},
  { profile_id: 9, liker_id: 16},
  { profile_id: 10, liker_id: 16},
  { profile_id: 11, liker_id: 16},
  { profile_id: 12, liker_id: 16},
  { profile_id: 13, liker_id: 16},
  { profile_id: 14, liker_id: 16},
  { profile_id: 15, liker_id: 16},
  ])
